<?php

namespace AppBundle\Repository;

/**
 * AdminGenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminGenRepository extends \Doctrine\ORM\EntityRepository
{
}
