<?php

namespace AppBundle\Repository;

/**
 * CenseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CenseurRepository extends \Doctrine\ORM\EntityRepository
{
}
