<?php

namespace AppBundle\Repository;

/**
 * ClasseMatiereProfesseurAnneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseMatiereProfesseurAnneeRepository extends \Doctrine\ORM\EntityRepository
{
}
