<?php

namespace AppBundle\Repository;

/**
 * ClasseMatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseMatiereRepository extends \Doctrine\ORM\EntityRepository
{
}
