<?php

namespace AppBundle\Repository;

/**
 * EleveParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveParentRepository extends \Doctrine\ORM\EntityRepository
{
}
