<?php

namespace AppBundle\Repository;

/**
 * NotificationProfesseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationProfesseurRepository extends \Doctrine\ORM\EntityRepository
{
}
