# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id:  fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_ADMIN_GENERAL:       [ROLE_USER]
        ROLE_CENSEUR:       [ROLE_USER]
        ROLE_PROFESSEUR:       [ ROLE_USER]
        ROLE_PARENT:       [ ROLE_PARENT]


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login
            remember_me:
                secret: '%secret%'

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
    - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/adminstration, role: [ROLE_ADMIN_GENERAL] }
    - { path: ^/ecole, role: [ROLE_CENSEUR] }
    - { path: ^/professeur, role: [ROLE_PROFESSEUR] }
    - { path: ^/parent, role: [ROLE_PARENT] }